resilience4j:
    ratelimiter:
        configs:
            default:
                limitForPeriod: 5
                limitRefreshPeriod: 2s
                timeoutDuration: 0
        instances:
            greetingRateLimit:
                baseConfig: default
                
